### PR TITLE
Hi! What do you think of my proposed changes?

### PR DESCRIPTION
**Pull request by arsenvlad**

### CODE REVIEW

**Review by Ma77o — COMMENTED** [review]
Could be better, but I'll allow it.

**Comment by Benjin** [comment]
I don't understand these changes.  They throw social courtesies to the wind by not asking how the other person is doing and confirming that they are themselves doing well.  The askee may find it rude, and feel valued only as a source for information and not as a human.

**Comment by arsenvlad** [comment]
@Benjin - I understood that the previous version was satirical/parody, but thought that the yeshello.org could be used in a better way :) as a more polite and less harsh version of nohello.com. In other words, nohello implies "hello is bad"... and I was hoping to use yeshello.org to achieve the same educational purpose but making it gentler and kinder than "NO hello"... I think you reverted the change back to how it was before... negating the goal I was hoping to achieve in having a "YES hello + Context". Hope this clarifies :) @Ma77o @Benjin @sammessina -- thoughts?

**Comment by Benjin** [comment]
@arsenvlad I'd say that there are many different "nohello"-style pages out there in various levels of politeness.  I enjoyed yeshello because it was the only satirical version I had come across, and was thus unique.  While I appreciate the goal of a more polite nohello, I think it's better as an independent site (e.g. "helpfulhello.org").  I think changing yeshello to literally the complete opposite loses the spirit of the page entirely.  It's one thing to tweak and refine, another to invert, ya know?

**Comment by arsenvlad** [comment]
If the original intent and spirit of the yeshello is specifically to be satirical versus practical, I completely understand. Since my PR was accepted by @sammessina I assumed that the intent of the site was open to pivoting :) Apologies for the extra churn on your end reverting it back.

**Pull request merged**
